### ISSUE TITLE
Won't mount fuse system if a program is running

### ISSUE THREAD

**Issue by Cediddi** [nickzoic/mpy-utils#1]
Hi,
I tried to mount my esp8266 to a folder. esp8266 has a line in boot.py that runs the main loop of my program. I checked your code, it does breaks the loop twice, then reboots and gets in the raw mode. It does restart the device but after restart, my code will run automatically. It should have break that too. I tried doing 'break break reboot break raw' but I guess micropython's boot procedure clears serial buffer, thus commands after reboot won't run at all.

Also, why do you reboot after each command?

**Comment by nickzoic** [comment]
Hi Cediddi, because of the quite cheesy way that mpy-utils uses to REPL to communicate, it is pretty limited in what it can do ...

**Comment by Cediddi** [comment]
After reading Ampy's source code I thought about writing a fuse adapter for esp8266, but then I found out this project.

It might be a cheesy way but it surely works as expected. I'll try to fix problems I might encounter in the future.
