### ISSUE TITLE
Missing scripts

### ISSUE THREAD

**Issue by haddadnidal** [nickzoic/mpy-utils#18]
Hi, thank you for you useful tool, 
I installed mpy-utils using pip3 and i have 2 scripts missing the mpy-download and the mpy-reset. 
here is a screenshot of my terminal 
![image](https://user-images.githubusercontent.com/9222035/73121424-45ede500-3f7a-11ea-85e9-5fdbaa0ab518.png)
thank you

**Comment by nickzoic** [comment]
G'day!  Yeah, I hadn't actually uploaded the latest version 0.1.12 to PyPI.
Thanks for the reminder.  Should be updated now ... if you run `pip install mpy-utils` again it should fix this and install the new utilities!
